/* English labels */
causeAvailableLanguage.en = {
    'cancel': 'Cancel',
    'changePassword': 'Change my password',
    'confirmChangedPassword': 'Your password has been changed, please log in again',
    'confirmPassword': 'Password confirmation',
    'copyright': '{version}All rights reserved © CAUCA',
    'email': 'Email',
    'emailSendWindowBlock': 'The email window appears to have been blocked at the opening!<br /><br />Please allow it to open in your browser<br />Or <a>click here</a>',
    'editor': 'Editor',
    'en': 'English',
    'english': 'English',
    'error': 'Error',
    'errorJQuery': 'Your browser is not supported! Please update',
    'errorLoginInformation': 'Please verify your login information',
    'errorOffline': 'Your browser doesn\'t support the offline mode',
    'errorUserMedia': 'Your browser doesn\'t support the audio/video recording',
    'errorVideoRecorder': 'An error occurred during video recording',
    'errorWebAudioRecorder': 'An error occurred during recording',
    'errorWorker': 'Your browser doesn\'t support the web worker.',
    'errorWorkerFileNotFound': 'Web worker file not found.',
    'fileDoesnotExist': 'This file does not seem to exist!',
    'fileLoadingError': 'An error occurred while loading the file!',
    'fileTypeBrowserNotSupported': 'This file type is not supported by your browser!',
    'fileTypeNotSupported': 'This file type is not supported!',
    'fileViewer': 'File viewer',
    'fr': 'French',
    'french': 'French',
    'fullscreen': 'Fullscreen',
    'header': '',
    'help': 'Help',
    'home': 'Home',
    'localStorage': 'Local storage',
    'localStorageNotAvailable': 'Local storage not available',
    'localStorageSetError': 'Error when saving on local storage',
    'login': 'Login',
    'logout': 'Logout',
    'logoutOf': 'Logout of ',
    'missingAddons': 'This addons can\'t be found in folder "cause/js/addons/"',
    'missingFile': 'A loaded file is missing',
    'missingPlugins': 'This plugins can\'t be found in folder "/plugins/"',
    'modify': 'Modify',
    'no': 'No',
    'offline': 'Offline',
    'ok': 'Ok',
    'offlineUpdate': 'A new version of this site is available. Load it?',
    'online': 'Online',
    'password': 'Password',
    'poweredBy': 'Powered by <div class="image minilogo" />',
    'replaceBy': 'Replace by',
    'sqlCantCreate': 'Can\'t create the database',
    'sqlNeedToDefineUpdate': 'You need to pass a "update" function',
    'sqlNotAvailable': 'Web database is not available',
    'sqlUpdateError': 'DB can\'t be updated',
    'sqlUpdateSucceed': 'DB has been updated',
    'sqlQueryError': 'An error occurs on query',
    'timeout': 'Timeout',
    'timeoutWebAudioRecorder': 'You exceeded the maximum accepted time',
    'toDefined': 'To defined',
    'translate': 'Translate',
    'update': 'Update',
    'username': 'Username',
    'version': 'Version',
    'wysiwyg': 'HTML editor',
    'yes': 'Yes',
    'yourBrowserDontSupport': 'Your browser doesn\'t support this option! Please update',
    'yourBrowserIsNotSupported': 'Your browser is not supported! Please update'
};