/* French labels */
causeAvailableLanguage.fr = {
    'cancel': 'Annuler',
    'changePassword': 'Modifier mon mot de passe',
    'confirmChangedPassword': 'Votre mot de passe à été modifié, veuillez-vous connecter à nouveau',
    'confirmPassword': 'Confirmation du mot de passe',
    'changePasswordError': 'Une erreur est survenue durant le changement de mot de passe, donc votre ancien mot de passe est toujours en place',
    'copyright': '{version}Tous droits réservés © CAUCA',
    'email': 'Courriel',
    'emailSendWindowBlock': 'La fenêtre de courriel semble avoir été bloqué à l\'ouverture!<br /><br />Veuillez permettre à celle-ci de s\'ouvrir dans votre navigateur.<br />Ou <a>cliquez ici</a>',
    'editor': 'Éditeur',
    'en': 'Anglais',
    'english': 'Anglais',
    'error': 'Erreur',
    'errorJQuery': 'Votre navigateur n\'est pas supporté! Veuillez le mettre à jour',
    'errorLoginInformation': 'Veuillez valider vos informations de connexion',
    'errorOffline': 'Votre navigateur ne supporte pas le mode hors ligne',
    'errorUserMedia': 'Votre navigateur ne supporte pas l\'enregistrement audio/vidéo',
    'errorVideoRecorder': 'Une erreur est survenue durant l\'enregistrement vidéo',
    'errorWebAudioRecorder': 'Une erreur est survenue durant l\'enregistrement',
    'errorWorker': 'Votre navigateur ne supporte pas les web worker.',
    'errorWorkerFileNotFound': 'Le fichier pour le web worker est introuvable.',
    'fileDoesnotExist': 'Ce fichier ne semble pas exister!',
    'fileLoadingError': 'Une erreur est survenue lors du chargement du fichier!',
    'fileTypeBrowserNotSupported': 'Ce type de fichier n\'est pas supporté par votre navigateur!',
    'fileTypeNotSupported': 'Ce type de fichier n\'est pas supporté!',
    'fileViewer': 'Visionneur de fichier',
    'fr': 'Français',
    'french': 'Français',
    'fullscreen': 'Plein écran',
    'header': '',
    'help': 'Aide',
    'home': 'Accueil',
    'localStorage': 'Stockage local',
    'localStorageNotAvailable': 'Stockage non disponible',
    'localStorageSetError': 'Erreur lors de la sauvegarde local',
    'login': 'Connexion',
    'logout': 'Déconnexion',
    'logoutOf': 'Déconnexion de ',
    'missingAddons': 'Ce addons n\'est pas présent dans le dossier "cause/js/addons/"',
    'missingFile': 'Un fichier chargé est manquant',
    'missingPlugins': 'Ce plugins n\'est pas présent dans le dossier "/plugins/"',
    'modify': 'Modifier',
    'no': 'Non',
    'offline': 'Hors ligne',
    'ok': 'Ok',
    'offlineUpdate': 'Une nouvelle version est disponible, Voulez-vous la charger?',
    'online': 'En ligne',
    'password': 'Mot de passe',
    'poweredBy': 'Propulsé par <div class="image minilogo" />',
    'replaceBy': 'Remplacer par',
    'sqlCantCreate': 'Impossible de créer la base de donnée',
    'sqlNeedToDefineUpdate': 'Vous devez créer une fonction pour la mise à jour',
    'sqlNotAvailable': 'La base de donnée web n\'est pas disponible',
    'sqlUpdateError': 'Impossible de mettre la BD à jour',
    'sqlUpdateSucceed': 'La BD a été mise à jour',
    'sqlQueryError': 'Une erreur est survenue lors de la requête',
    'timeout': 'Délai écouler',
    'timeoutWebAudioRecorder': 'Vous avez dépassé le temps maximum accepté',
    'toDefined': 'À définir',
    'translate': 'Traduction',
    'update': 'Mise à jour',
    'username': 'Nom d\'utilisateur',
    'version': 'Version',
    'wysiwyg': 'Éditeur HTML',
    'yes': 'Oui',
    'yourBrowserDontSupport': 'Votre navigateur ne supporte pas cette option! Veuillez le mettre à jour',
    'yourBrowserIsNotSupported': 'Votre navigateur n\'est pas supporté! Veuillez le mettre à jour'
};